### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by waynep16** [leonstafford/static-html-output#149]
`
Fatal error: Uncaught Error: Class 'StaticHTMLOutput\Controller' not found in /home/g6/public_html/wp-content/plugins/static-html-output-master/static-html-output-plugin.php:26 Stack trace: #0 /home/g6/public_html/wp-admin/includes/plugin.php(2297): include() #1 /home/g6/public_html/wp-admin/plugins.php(191): plugin_sandbox_scrape('static-html-out...') #2 {main} thrown in /home/g6/public_html/wp-content/plugins/static-html-output-master/static-html-output-plugin.php on line 26`

**Comment by mooseyoose** [comment]
Also having this issue

**Comment by mackenzienolan** [comment]
Fatal error: Uncaught Error: Class 'StaticHTMLOutput\Controller' not found in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/static-html-output-master/static-html-output-plugin.php:26 Stack trace: #0 /opt/bitnami/apps/wordpress/htdocs/wp-admin/includes/plugin.php(2255): include() #1 /opt/bitnami/apps/wordpress/htdocs/wp-admin/plugins.php(177): plugin_sandbox_scrape('static-html-out...') #2 {main} thrown in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/static-html-output-master/static-html-output-plugin.php on line 26

**Comment by thegulshankumar** [comment]
Try on PHP 7.4
