### ISSUE TITLE
new error exporting to github in 6.3

### ISSUE THREAD

**Issue by dmeagor** [leonstafford/static-html-output#174]
2019-01-23 01:10:14
PHP VERSION 7.2.13
OS VERSION Linux ams203.hawkhost.com 2.6.32-896.16.1.lve1.4.49.el6.x86_64 leonstafford/wp2static#1 SMP Fri Jan 5 05:15:23 EST 2018 x86_64
WP VERSION 5.0.3
WP URL http://xxxx.xxxx.co.uk
WP SITEURL http://xxxx.xxxx.co.uk
WP HOME http://xxxx.xxxx.co.uk
WP ADDRESS http://xxxx.xxxx.co.uk
PLUGIN VERSION 6.3
VIA WP-CLI? 
STATIC EXPORT URL https://xxxx.xxxx2.com/
SAVING URL: FILE IS EMPTY /favicon.ico
BAD RESPONSE STATUS (404): http://PLACEHOLDER.wpsho/
BAD RESPONSE STATUS FROM API (502)
Deployment: error encountered
Exception: BAD RESPONSE STATUS FROM API (502) in /home/wpstagep/xxxx.xxxx.co.uk/wp-content/plugins/static-html-output-plugin/library/StaticHtmlOutput/SitePublisher.php:312
Stack trace:
#0 /home/wpstagep/xxxx.xxxx.co.uk/wp-content/plugins/static-html-output-plugin/powerpack/GitHub.php(290): StaticHtmlOutput_SitePublisher->checkForValidResponses(502, Array)
leonstafford/wp2static#1 /home/wpstagep/xxxx.xxxx.co.uk/wp-content/plugins/static-html-output-plugin/powerpack/GitHub.php(91): StaticHtmlOutput_GitHub->updateFileInGitHub()
leonstafford/wp2static#2 /home/wpstagep/xxxx.xxxx.co.uk/wp-content/plugins/static-html-output-plugin/powerpack/GitHub.php(31): StaticHtmlOutput_GitHub->upload_files()
leonstafford/wp2static#3 /home/wpstagep/xxxx.xxxx.co.uk/wp-content/plugins/static-html-output-plugin/powerpack/GitHub.php(352): StaticHtmlOutput_GitHub->__construct()
leonstafford/wp2static#4 /home/wpstagep/xxxx.xxxx.co.uk/wp-content/plugins/static-html-output-plugin/library/StaticHtmlOutput/Dispatcher.php(42): require_once('/home/wpstagep/...')
leonstafford/wp2static#5 /home/wpstagep/xxxx.xxxx.co.uk/wp-content/plugins/static-html-output-plugin/wp2static.php(17): require_once('/home/wpstagep/...')
leonstafford/wp2static#6 /home/wpstagep/xxxx.xxxx.co.uk/wp-settings.php(322): include_once('/home/wpstagep/...')
leonstafford/wp2static#7 /home/wpstagep/xxxx.xxxx.co.uk/wp-config.php(86): require_once('/home/wpstagep/...')
leonstafford/wp2static#8 /home/wpstagep/xxxx.xxxx.co.uk/wp-load.php(37): require_once('/home/wpstagep/...')
leonstafford/wp2static#9 /home/wpstagep/xxxx.xxxx.co.uk/wp-admin/admin-ajax.php(22): require_once('/home/wpstagep/...')
leonstafford/wp2static#10 {main}

**Comment by HeyNitin** [comment]
2021-03-27 01:01:53 	 2021-03-26 07:31:53
PHP VERSION 7.4.13
OS VERSION Windows NT NITINS-PC 10.0 build 19042 (Windows 10) AMD64
WP VERSION 5.7
WP URL http://localhost/wordpress
WP SITEURL http://localhost/wordpress
WP HOME http://localhost/wordpress
WP ADDRESS http://localhost/wordpress
PLUGIN VERSION 6.6.21
VIA WP-CLI? 
STATIC EXPORT URL https://07nitin07.github.io/Decoding-D-Street
PERMALINK STRUCTURE /%postname%/
SERVER SOFTWARE Apache/2.4.46 (Win64) OpenSSL/1.1.1h PHP/7.4.13 	
2021-03-27 01:01:53 	 Active plugins: 	
2021-03-27 01:01:53 	 addons-for-elementor/addons-for-elementor.php 	
2021-03-27 01:01:53 	 all-in-one-wp-migration/all-in-one-wp-migration.php 	
2021-03-27 01:01:53 	 astra-sites/astra-sites.php 	
2021-03-27 01:01:53 	 elementor/elementor.php 	
2021-03-27 01:01:53 	 static-html-output-plugin/static-html-output-plugin.php 	
2021-03-27 01:01:53 	 wpforms-lite/wpforms.php 	
2021-03-27 01:01:53 	 Plugin options: 	
2021-03-27 01:01:54 	 additionalUrls:  	
2021-03-27 01:01:54 	 baseUrl:  	
2021-03-27 01:01:54 	 baseUrl-bitbucket:  	
2021-03-27 01:01:54 	 baseUrl-bunnycdn:  	
2021-03-27 01:01:54 	 baseUrl-github:  	
2021-03-27 01:01:54 	 baseUrl-gitlab:  	
2021-03-27 01:01:54 	 baseUrl-netlify:  	
2021-03-27 01:01:54 	 baseUrl-s3:  	
2021-03-27 01:01:54 	 baseUrl-zip:  	
2021-03-27 01:01:54 	 baseUrl-zip:  	
2021-03-27 01:01:54 	 basicAuthPassword: ******************* 	
2021-03-27 01:01:54 	 basicAuthUser:  	
2021-03-27 01:01:54 	 bbBranch:  	
2021-03-27 01:01:54 	 bbRepo:  	
2021-03-27 01:01:54 	 bbToken: ******************* 	
2021-03-27 01:01:54 	 bunnycdnStorageZoneAccessKey: ******************* 	
2021-03-27 01:01:55 	 bunnycdnPullZoneAccessKey: ******************* 	
2021-03-27 01:01:55 	 bunnycdnPullZoneID:  	
2021-03-27 01:01:55 	 bunnycdnStorageZoneName:  	
2021-03-27 01:01:55 	 bunnycdn_api_host: ******************* 	
2021-03-27 01:01:55 	 cfDistributionId:  	
2021-03-27 01:01:55 	 completionEmail:  	
2021-03-27 01:01:55 	 crawl_delay:  	
2021-03-27 01:01:55 	 crawl_increment:  	
2021-03-27 01:01:55 	 crawlPort:  	
2021-03-27 01:01:56 	 delayBetweenAPICalls:  	
2021-03-27 01:01:56 	 deployBatchSize:  	
2021-03-27 01:01:56 	 excludeURLs:  	
2021-03-27 01:01:56 	 ghBranch:  	
2021-03-27 01:01:56 	 ghCommitMessage:  	
2021-03-27 01:01:56 	 ghRepo:  	
2021-03-27 01:01:56 	 ghToken: ******************* 	
2021-03-27 01:01:56 	 glBranch:  	
2021-03-27 01:01:56 	 glProject:  	
2021-03-27 01:01:56 	 glToken: ******************* 	
2021-03-27 01:01:56 	 netlifyHeaders:  	
2021-03-27 01:01:56 	 netlifyPersonalAccessToken: ******************* 	
2021-03-27 01:01:56 	 netlifyRedirects:  	
2021-03-27 01:01:57 	 netlifySiteID:  	
2021-03-27 01:01:57 	 removeConditionalHeadComments: 1 	
2021-03-27 01:01:57 	 removeHTMLComments: 1 	
2021-03-27 01:01:57 	 removeWPLinks: 1 	
2021-03-27 01:01:57 	 removeWPMeta: 1 	
2021-03-27 01:01:57 	 rewrite_rules:  	
2021-03-27 01:01:57 	 rename_rules:  	
2021-03-27 01:01:57 	 s3Bucket:  	
2021-03-27 01:01:57 	 s3Key:  	
2021-03-27 01:01:57 	 s3Region:  	
2021-03-27 01:01:57 	 s3Secret: ******************* 	
2021-03-27 01:01:57 	 selected_deployment_option:  	
2021-03-27 01:01:57 	 targetFolder:  	
2021-03-27 01:01:57 	 useBasicAuth:  	
2021-03-27 01:01:57 	 Installed extensions: 	
2021-03-27 01:01:58 	 Core,bcmath,calendar,ctype,date,filter,hash,iconv,json,SPL,pcre,readline,Reflection,session,standard,mysqlnd,tokenizer,zip,zlib,libxml,dom,PDO,bz2,SimpleXML,xml,xmlreader,xmlwriter,apache2handler,openssl,curl,fileinfo,gd,gettext,mbstring,exif,mysqli,pdo_mysql,pdo_sqlite,Phar,ftp 	
2021-03-27 01:02:05 	 BAD RESPONSE STATUS (404): /ads.txt 	
2021-03-27 01:02:06 	 BAD RESPONSE STATUS (404): /astra-2/ 	
2021-03-27 01:02:07 	 BAD RESPONSE STATUS (404): /astra-3/ 	
2021-03-27 01:02:10 	 BAD RESPONSE STATUS (404): /astra-4/ 	
2021-03-27 01:02:11 	 BAD RESPONSE STATUS (404): /astra-5/ 	
2021-03-27 01:02:12 	 BAD RESPONSE STATUS (404): /astra-6/ 	
2021-03-27 01:02:13 	 BAD RESPONSE STATUS (404): /astra-7/ 	
2021-03-27 01:02:14 	 BAD RESPONSE STATUS (404): /astra/ 	
2021-03-27 01:02:26 	 BAD RESPONSE STATUS (404): /favicon.ico 	
2021-03-27 01:02:28 	 BAD RESPONSE STATUS (404): /hestia/ 	
2021-03-27 01:02:32 	 BAD RESPONSE STATUS (404): /robots.txt 	
2021-03-27 01:02:38 	 BAD RESPONSE STATUS (404): /twentytwentyone/ 	
2021-03-27 01:02:40 	 BAD RESPONSE STATUS (404): /wordpress/ 	
2021-03-27 01:02:41 	 BAD RESPONSE STATUS (404): /wordpress/2021/ 	
2021-03-27 01:02:43 	 BAD RESPONSE STATUS (404): /wordpress/2021/03/ 	
2021-03-27 01:02:44 	 BAD RESPONSE STATUS (404): /wordpress/2021/03/25/ 	
2021-03-27 01:02:47 	 BAD RESPONSE STATUS (404): /wordpress/astra-2/ 	
2021-03-27 01:02:48 	 BAD RESPONSE STATUS (404): /wordpress/astra-3/ 	
2021-03-27 01:02:50 	 BAD RESPONSE STATUS (404): /wordpress/astra-4/ 	
2021-03-27 01:02:52 	 BAD RESPONSE STATUS (404): /wordpress/astra-5/ 	
2021-03-27 01:02:53 	 BAD RESPONSE STATUS (404): /wordpress/astra-6/ 	
2021-03-27 01:02:54 	 BAD RESPONSE STATUS (404): /wordpress/astra-7/ 	
2021-03-27 01:02:57 	 BAD RESPONSE STATUS (404): /wordpress/astra/ 	
2021-03-27 01:03:04 	 BAD RESPONSE STATUS (404): /wordpress/hestia/ 	
2021-03-27 01:03:14 	 BAD RESPONSE STATUS (404): /wordpress/twentytwentyone/ 	
2021-03-27 01:03:46 	 BAD RESPONSE STATUS (404): /wp-content/uploads/2019/06/feature3-free-img.png 	
2021-03-27 01:03:59 	 Failed saving /wp-json/ to C:\xampp\htdocs\wordpress/wp-content/uploads/static-html-output/\/wp-json/index. 	
2021-03-27 01:03:59 	 BAD RESPONSE STATUS (400): /wp-json/oembed/1.0/embed 	
2021-03-27 01:04:01 	 Failed saving /wp-json/wp/v2/categories/6 to C:\xampp\htdocs\wordpress/wp-content/uploads/static-html-output/wp-json/wp/v2/categories/6/index. 	
2021-03-27 01:04:03 	 Failed saving /wp-json/wp/v2/pages/5 to C:\xampp\htdocs\wordpress/wp-content/uploads/static-html-output/wp-json/wp/v2/pages/5/index. 	
2021-03-27 01:04:07 	 Failed saving /wp-json/wp/v2/pages/540 to C:\xampp\htdocs\wordpress/wp-content/uploads/static-html-output/wp-json/wp/v2/pages/540/index. 	
2021-03-27 01:04:08 	 Failed saving /wp-json/wp/v2/pages/541 to C:\xampp\htdocs\wordpress/wp-content/uploads/static-html-output/wp-json/wp/v2/pages/541/index. 	
2021-03-27 01:04:09 	 Failed saving /wp-json/wp/v2/pages/6 to C:\xampp\htdocs\wordpress/wp-content/uploads/static-html-output/wp-json/wp/v2/pages/6/index. 	
2021-03-27 01:04:11 	 Failed saving /wp-json/wp/v2/pages/7 to C:\xampp\htdocs\wordpress/wp-content/uploads/static-html-output/wp-json/wp/v2/pages/7/index. 	
2021-03-27 01:04:12 	 Failed saving /wp-json/wp/v2/posts/712 to C:\xampp\htdocs\wordpress/wp-content/uploads/static-html-output/wp-json/wp/v2/posts/712/index. 	
2021-03-27 01:04:14 	 Failed saving /wp-json/wp/v2/posts/766 to C:\xampp\htdocs\wordpress/wp-content/uploads/static-html-output/wp-json/wp/v2/posts/766/index. 	
2021-03-27 01:04:15 	 Failed saving /wp-json/wp/v2/users/1 to C:\xampp\htdocs\wordpress/wp-content/uploads/static-html-output/wp-json/wp/v2/users/1/index. 	


So what's the issue here?
